/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20210905 of the Motif Metadata Standard
 */
export interface MotifSpace20210905 { 
  spaceType: string; 
  blockchain: string; 
  name: string; 
  description: string; 
  mimeType: string; 
  data: string; 
  access: string;
  version: string;
}
