/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20210905 of the Motif Metadata Standard
 */
export interface MotifSpace20210905 {
  /**
   * Type of the NFT Item
   */
  spaceType: string;
  /**
   * Owned NFT item
   */
  blockchain: string;
  /**
   * Name of the NFT Item
   */
  name: string;
  /**
   * Description of the NFT Item
   */
  description: string;
  /**
   * MimeType of NFT Item
   */
  mimeType: string;

  code: string;
  data: string;
  /**
   * Blockchain of the NFT item under the item type
   */

  access: string;
  version: string;
}
